version: '3'

services:
  php-workspace:
    container_name: lab1-php
    build: ./php
    restart: always
    depends_on:
      - mysql-db
    volumes:
      - ./code:/var/www/html/
    networks: 
      - front
      - back

  nginx:
    container_name: lab1-nginx
    build: ./nginx
    restart: always
    depends_on:
      - php-workspace
      - mysql-db
    ports:
      - "8080:8080"
    volumes:
      - ./log/nginx:/var/log/nginx/
    networks: 
      - front

  mysql-db:
    container_name: lab1-mysql
    #image: mysql:5.7
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    networks: 
      - back

networks: 
  front:
    driver: "bridge"
  back:
    driver: "bridge"
