version: '3'

services:
  php-workspace:
    image: docker-php_php-workspace:latest
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mysql-db
    volumes:
      - ./code:/var/www/html/
    networks: 
      - front
      - back

  nginx:
    image: docker-php_nginx:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits: 
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      mode: replicated
      replicas: 3
    depends_on:
      - php-workspace
      - mysql-db
    ports:
      - "8080:8080"
    volumes:
      - ./log/nginx:/var/log/nginx/
    networks: 
      - front

  mysql-db:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits: 
          cpus: '0.50' # 50% of a single core
          memory: 50M # no more than 50M of memory
        reservations:
          cpus: '0.25' # 25% CPU time reserved
          memory: 20M # 20M of memory reserved
      placement:
        constraints: 
          - node.role == manager
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - ./mysql/db_data:/var/lib/mysql/
      - ./log/mysql:/var/log/mysql/
      - ./mysql/init:/docker-entrypoint-initdb.d/
    networks: 
      - back

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9090:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.role == manager

networks: 
  front:
    driver: "overlay"
  back:
    driver: "overlay"
